--таблица размеров поля
CREATE TABLE PUZZLE_SIZES (
    ID  NUMBER  CONSTRAINT PK_PUZZLE_SIZES PRIMARY KEY,
    GRID_SIZE NUMBER(2) NOT NULL CONSTRAINT CHK_PS_SIZE CHECK (GRID_SIZE BETWEEN 3 AND 7),
    DEFAULT_TIME_LIMIT INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    CONSTRAINT UQ_PS_GRID_SIZE UNIQUE (GRID_SIZE)
);
-- таблица уровней сложности
CREATE TABLE DIFFICULTY_LEVELS (
    ID  NUMBER CONSTRAINT PK_DIFF_LEVELS PRIMARY KEY,
    NAME VARCHAR2(20)NOT NULL CONSTRAINT CHK_DL_NAME CHECK (NAME IN ('Easy','Medium','Hard')),
    SHUFFLE_MOVES  NUMBER(6)NOT NULL CONSTRAINT CHK_DL_SM CHECK (SHUFFLE_MOVES > 0),
    CONSTRAINT UQ_DL_NAME UNIQUE (NAME)
);
-- таблица статуса игры
CREATE TABLE GAME_STATUSES (
    ID NUMBER CONSTRAINT PK_GAME_STATUSES PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT UQ_GSTAT_NAME UNIQUE (NAME)
);
-- таблица типа действия
CREATE TABLE ACTION_TYPES (
    ID NUMBER CONSTRAINT PK_ACTION_TYPES PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT UQ_AT_NAME UNIQUE (NAME)
);
-- таблица пользователей
CREATE TABLE USERS (
    ID NUMBER CONSTRAINT PK_USERS PRIMARY KEY,
    DB_USERNAME VARCHAR2(128) NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(255),
    GAMES_COUNT NUMBER(6) DEFAULT 0 NOT NULL CONSTRAINT CHK_USR_GC CHECK (GAMES_COUNT >= 0),
    FIRST_GAME_DATE DATE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_USERS_DBNAME UNIQUE (DB_USERNAME),
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CHK_USERS_EMAIL CHECK (EMAIL IS NULL OR REGEXP_LIKE(EMAIL, '^[^@]+@[^@]+\.[^@]+$'))
);

-- таблица каталога головоломок
CREATE TABLE PUZZLES (
    ID NUMBER CONSTRAINT PK_PUZZLES PRIMARY KEY,
    PUZZLE_SIZE_ID NUMBER NOT NULL CONSTRAINT FK_PZ_SIZE REFERENCES PUZZLE_SIZES (ID),
    DIFFICULTY_ID NUMBER NOT NULL CONSTRAINT FK_PZ_DIFF REFERENCES DIFFICULTY_LEVELS (ID),
    SEED VARCHAR2(100) NOT NULL,
    IS_DAILY NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT CHK_PZ_DAILY CHECK (IS_DAILY IN (0, 1)),
    INITIAL_STATE CLOB NOT NULL CONSTRAINT CHK_PZ_INIT CHECK (INITIAL_STATE IS JSON),
    TARGET_STATE CLOB NOT NULL CONSTRAINT CHK_PZ_TGT CHECK (TARGET_STATE IS JSON),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_PZ_SEED_SIZE UNIQUE (SEED, PUZZLE_SIZE_ID)
);


-- таблица сессий перемешивания (для воспроизводимости по seed)
CREATE TABLE SHUFFLE_SESSIONS (
    ID NUMBER CONSTRAINT PK_SHUFFLE_SESSIONS PRIMARY KEY,
    PUZZLE_ID NUMBER NOT NULL CONSTRAINT FK_SHS_PUZZLE REFERENCES PUZZLES (ID),
    SEED VARCHAR2(100) NOT NULL,
    SHUFFLE_MOVES_COUNT NUMBER(6) NOT NULL CONSTRAINT CHK_SHS_SMC CHECK (SHUFFLE_MOVES_COUNT > 0),
    SHUFFLE_SEQUENCE CLOB CONSTRAINT CHK_SHS_SEQ CHECK (SHUFFLE_SEQUENCE IS NULL OR SHUFFLE_SEQUENCE IS JSON),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_SHS_SEED_PUZZLE UNIQUE (SEED, PUZZLE_ID)
);


-- таблица игровых сессий
CREATE TABLE GAME_SESSIONS (
    ID NUMBER CONSTRAINT PK_GAME_SESSIONS PRIMARY KEY,
    USER_ID NUMBER NOT NULL CONSTRAINT FK_GSESS_USER REFERENCES USERS (ID),
    PUZZLE_ID NUMBER NOT NULL CONSTRAINT FK_GSESS_PUZZLE REFERENCES PUZZLES (ID),
    STATUS_ID NUMBER NOT NULL CONSTRAINT FK_GSESS_STATUS REFERENCES GAME_STATUSES (ID),
    SESSION_TOKEN VARCHAR2(255) NOT NULL,
    STEPS_COUNT NUMBER(6) DEFAULT 0 NOT NULL CONSTRAINT CHK_GSESS_SC CHECK (STEPS_COUNT >= 0),
    LAST_ACTIVITY_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    START_TIME DATE NOT NULL,
    END_TIME DATE,
    CONSTRAINT UQ_GSESS_TOKEN UNIQUE (SESSION_TOKEN)
);

-- таблица  игровых попыток
CREATE TABLE GAME_ATTEMPTS (
    ID NUMBER CONSTRAINT PK_GAME_ATTEMPTS PRIMARY KEY,
    SESSION_ID NUMBER NOT NULL CONSTRAINT FK_GA_SESSION REFERENCES GAME_SESSIONS (ID),
    USER_ID NUMBER NOT NULL CONSTRAINT FK_GA_USER REFERENCES USERS (ID),
    PUZZLE_ID NUMBER NOT NULL CONSTRAINT FK_GA_PUZZLE REFERENCES PUZZLES (ID),
    SHUFFLE_SESSION_ID NUMBER CONSTRAINT FK_GA_SHUFFLE REFERENCES SHUFFLE_SESSIONS (ID),
    GAME_MODE VARCHAR2(20) DEFAULT 'numbers' NOT NULL CONSTRAINT CHK_GA_MODE CHECK (GAME_MODE IN ('numbers', 'images')),
    CURRENT_STATE CLOB NOT NULL CONSTRAINT CHK_GA_CUR CHECK (CURRENT_STATE IS JSON),
    INITIAL_MISPLACED_TILES NUMBER(4) NOT NULL,
    INITIAL_MANHATTAN_DISTANCE NUMBER(6) NOT NULL,
    CURRENT_MISPLACED_TILES NUMBER(4) NOT NULL,
    CURRENT_MANHATTAN_DISTANCE NUMBER(6) NOT NULL,
    UNDO_POINTER NUMBER(6) DEFAULT 0 NOT NULL,
    STATUS_ID NUMBER NOT NULL CONSTRAINT FK_GA_STATUS REFERENCES GAME_STATUSES (ID),
    TIME_LIMIT INTERVAL DAY(0) TO SECOND(0),
    STARTED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    FINISHED_AT TIMESTAMP WITH TIME ZONE
);


-- таблица истории ходов
CREATE TABLE GAME_STEPS (
    ID NUMBER CONSTRAINT PK_GAME_STEPS PRIMARY KEY,
    SESSION_ID NUMBER NOT NULL CONSTRAINT FK_GS_SESSION REFERENCES GAME_SESSIONS (ID) ON DELETE CASCADE,
    ATTEMPT_ID NUMBER NOT NULL CONSTRAINT FK_GS_ATTEMPT REFERENCES GAME_ATTEMPTS (ID) ON DELETE CASCADE,
    ACTION_ID NUMBER NOT NULL CONSTRAINT FK_GS_ACTION REFERENCES ACTION_TYPES (ID),
    TILE_VALUE NUMBER(3),
    DIRECTION VARCHAR2(5) CONSTRAINT CHK_GS_DIR CHECK (DIRECTION IS NULL OR DIRECTION IN ('up', 'down', 'left', 'right')),
    STATE_AFTER CLOB CONSTRAINT CHK_GS_STATE CHECK (STATE_AFTER IS NULL OR STATE_AFTER IS JSON),
    IS_ACTUAL NUMBER(1) DEFAULT 1 NOT NULL CONSTRAINT CHK_GS_ACTUAL CHECK (IS_ACTUAL IN (0, 1)),
    IS_IMPORT NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT CHK_GS_IMPORT CHECK (IS_IMPORT IN (0, 1)),
    IS_MARK NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT CHK_GS_MARK CHECK (IS_MARK IN (0, 1)),
    STEP_INDEX NUMBER(6) NOT NULL CONSTRAINT CHK_GS_IDX CHECK (STEP_INDEX >= 0),
    STEP_TIME DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UQ_GS_ATTEMPT_IDX UNIQUE (ATTEMPT_ID, STEP_INDEX)
);


-- таблица метрики прогресса
CREATE TABLE ATTEMPT_METRICS (
    ID NUMBER CONSTRAINT PK_ATTEMPT_METRICS PRIMARY KEY,
    ATTEMPT_ID NUMBER NOT NULL CONSTRAINT FK_AM_ATTEMPT REFERENCES GAME_ATTEMPTS (ID) ON DELETE CASCADE,
    RECORDED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    STEP_INDEX NUMBER(6) NOT NULL,
    MOVES_COUNT NUMBER(6) NOT NULL,
    TIME_ELAPSED INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    MISPLACED_TILES NUMBER(4) NOT NULL,
    MANHATTAN_DISTANCE NUMBER(6) NOT NULL,
    CORRECT_TILES NUMBER(4) NOT NULL,
    PROGRESS_PCT NUMBER(5, 2) CONSTRAINT CHK_MET_PCT CHECK (PROGRESS_PCT BETWEEN 0 AND 100)
);


-- таблица журнал событий
CREATE TABLE LOGS (
    ID NUMBER CONSTRAINT PK_LOGS PRIMARY KEY,
    LOG_DATE DATE DEFAULT SYSDATE NOT NULL,
    SESSION_ID NUMBER CONSTRAINT FK_LOG_SESSION REFERENCES GAME_SESSIONS (ID),
    LOG_TYPE VARCHAR2(20) NOT NULL CONSTRAINT CHK_LOG_TYPE CHECK (LOG_TYPE IN ('ERROR', 'INFO', 'DEBUG', 'WARN')),
    PROCEDURE_NAME VARCHAR2(200),
    MESSAGE VARCHAR2(4000)
);

SELECT DISTINCT owner FROM all_objects;

SELECT TABLE_name FROM all_tables WHERE owner = 'SYSTEM'

SELECT * FROM GAME_STATUSES;

CREATE SEQUENCE SEQ_PUZZLE_SIZES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DIFF_LEVELS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GAME_STATUSES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ACTION_TYPES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PUZZLES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SHUFFLE_SESSIONS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GAME_SESSIONS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GAME_ATTEMPTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GAME_STEPS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ATTEMPT_METRICS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LOGS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


COMMENT ON TABLE  PUZZLE_SIZES IS 'Допустимые размеры игрового поля N×N';
COMMENT ON COLUMN PUZZLE_SIZES.GRID_SIZE IS 'Длина стороны поля (3..7)';
COMMENT ON COLUMN PUZZLE_SIZES.DEFAULT_TIME_LIMIT IS 'Лимит времени по умолчанию для данного размера';


