CREATE OR REPLACE VIEW V_TOP_PLAYERS AS
SELECT 
    U.ID,
    U.USERNAME,
    COUNT(DISTINCT GS.ID) AS TOTAL_GAMES,
    SUM(CASE WHEN GST.NAME = 'solved' THEN 1 ELSE 0 END) AS SOLVED_GAMES,
    ROUND(
        SUM(CASE WHEN GST.NAME = 'solved' THEN 1 ELSE 0 END) / 
        NULLIF(COUNT(DISTINCT GS.ID), 0) * 100, 2
    ) AS SUCCESS_RATE,
    AVG(
        CASE WHEN GST.NAME = 'solved'
             THEN EXTRACT(HOUR FROM (GS.END_TIME - GS.START_TIME)) * 60 + 
                  EXTRACT(MINUTE FROM (GS.END_TIME - GS.START_TIME))
        END
    ) AS AVG_TIME_MINUTES,
    MIN(
        CASE WHEN GST.NAME = 'solved' 
             THEN GS.STEPS_COUNT 
        END
    ) AS BEST_STEPS
FROM USERS U
LEFT JOIN GAME_SESSIONS GS ON U.ID = GS.USER_ID
LEFT JOIN GAME_STATUSES GST ON GS.STATUS_ID = GST.ID
WHERE (GST.NAME != 'active' OR GST.NAME IS NULL)
GROUP BY U.ID, U.USERNAME;


-- V_TOP_PLAYERS


CREATE OR REPLACE VIEW V_TOP_PLAYERS AS
SELECT
    U.ID,
    U.USERNAME,
    COUNT(DISTINCT GS.ID) AS TOTAL_GAMES,
    SUM(CASE WHEN GST.NAME = 'solved' THEN 1 ELSE 0 END) AS SOLVED_GAMES,
    ROUND(
        SUM(CASE WHEN GST.NAME = 'solved' THEN 1 ELSE 0 END) /
        NULLIF(COUNT(DISTINCT GS.ID), 0) * 100, 2
    ) AS SUCCESS_RATE,
    ROUND(AVG(
        CASE WHEN GST.NAME = 'solved'
             THEN (GS.END_TIME - GS.START_TIME) * 24 * 60
        END
    ), 2) AS AVG_TIME_MINUTES,
    MIN(
        CASE WHEN GST.NAME = 'solved'
             THEN GS.STEPS_COUNT
        END
    ) AS BEST_STEPS
FROM USERS U
LEFT JOIN GAME_SESSIONS GS ON U.ID = GS.USER_ID
LEFT JOIN GAME_STATUSES GST ON GS.STATUS_ID = GST.ID
WHERE (GST.NAME != 'active' OR GST.NAME IS NULL)
GROUP BY U.ID, U.USERNAME;


--V_GAME_STATUS

CREATE OR REPLACE VIEW V_GAME_STATUS AS
SELECT
    GS.ID AS SESSION_ID,
    U.USERNAME,
    PS.GRID_SIZE,
    DL.NAME AS DIFFICULTY,
    GST.NAME AS STATUS,
    GS.STEPS_COUNT AS TOTAL_STEPS,
    GA.UNDO_POINTER AS CURRENT_STEP,
    GA.CURRENT_MISPLACED_TILES AS MISPLACED_TILES,
    GA.CURRENT_MANHATTAN_DISTANCE AS MANHATTAN_DISTANCE,
    GA.INITIAL_MANHATTAN_DISTANCE AS INITIAL_MANHATTAN,
    CASE
        WHEN GA.INITIAL_MANHATTAN_DISTANCE > 0
        THEN ROUND(
            (GA.INITIAL_MANHATTAN_DISTANCE - GA.CURRENT_MANHATTAN_DISTANCE) /
            GA.INITIAL_MANHATTAN_DISTANCE * 100, 1
        )
        ELSE 100
    END AS PROGRESS_PCT,
    ROUND((SYSDATE - GS.START_TIME) * 24 * 60, 1) AS ELAPSED_MINUTES,
    GA.TIME_LIMIT,
    GS.START_TIME,
    GS.LAST_ACTIVITY_AT
FROM GAME_SESSIONS GS
JOIN USERS U ON GS.USER_ID = U.ID
JOIN GAME_STATUSES GST ON GS.STATUS_ID = GST.ID
JOIN PUZZLES PZ ON GS.PUZZLE_ID = PZ.ID
JOIN PUZZLE_SIZES PS ON PZ.PUZZLE_SIZE_ID = PS.ID
JOIN DIFFICULTY_LEVELS DL ON PZ.DIFFICULTY_ID = DL.ID
JOIN GAME_ATTEMPTS GA ON GA.SESSION_ID = GS.ID
    AND GA.STATUS_ID = (SELECT ID FROM GAME_STATUSES WHERE NAME = 'active')
WHERE GST.NAME = 'active';


-- V_BOARD

CREATE OR REPLACE VIEW V_BOARD AS
SELECT
    GS.ID AS SESSION_ID,
    U.USERNAME,
    PS.GRID_SIZE,
    GA.CURRENT_STATE AS BOARD_STATE,
    GA.UNDO_POINTER AS MOVE_NUMBER,
    CASE WHEN PZ.IS_DAILY = 1 THEN 'Да' ELSE 'Нет' END AS IS_DAILY
FROM GAME_SESSIONS GS
JOIN USERS U ON GS.USER_ID = U.ID
JOIN GAME_STATUSES GST ON GS.STATUS_ID = GST.ID
JOIN PUZZLES PZ ON GS.PUZZLE_ID = PZ.ID
JOIN PUZZLE_SIZES PS ON PZ.PUZZLE_SIZE_ID = PS.ID
JOIN GAME_ATTEMPTS GA ON GA.SESSION_ID = GS.ID
    AND GA.STATUS_ID = (SELECT ID FROM GAME_STATUSES WHERE NAME = 'active')
WHERE GST.NAME = 'active';


-- V_HISTORY

CREATE OR REPLACE VIEW V_HISTORY AS
SELECT
    GS.SESSION_ID,
    GSESS.START_TIME AS SESSION_START,
    U.USERNAME,
    PS.GRID_SIZE,
    DL.NAME AS DIFFICULTY,
    GS.STEP_INDEX,
    AT.NAME AS ACTION,
    GS.TILE_VALUE,
    GS.DIRECTION,
    GS.STEP_TIME,
    GS.IS_ACTUAL,
    GS.IS_IMPORT,
    GS.IS_MARK
FROM GAME_STEPS GS
JOIN ACTION_TYPES AT ON GS.ACTION_ID = AT.ID
JOIN GAME_SESSIONS GSESS ON GS.SESSION_ID = GSESS.ID
JOIN USERS U ON GSESS.USER_ID = U.ID
JOIN PUZZLES PZ ON GSESS.PUZZLE_ID = PZ.ID
JOIN PUZZLE_SIZES PS ON PZ.PUZZLE_SIZE_ID = PS.ID
JOIN DIFFICULTY_LEVELS DL ON PZ.DIFFICULTY_ID = DL.ID
ORDER BY GS.SESSION_ID, GS.STEP_INDEX;


-- V_PUZZLES

CREATE OR REPLACE VIEW V_PUZZLES AS
SELECT
    PZ.ID,
    PZ.SEED,
    PS.GRID_SIZE,
    DL.NAME AS DIFFICULTY,
    DL.SHUFFLE_MOVES,
    PS.DEFAULT_TIME_LIMIT,
    CASE WHEN PZ.IS_DAILY = 1 THEN 'Да' ELSE 'Нет' END AS IS_DAILY,
    PZ.CREATED_AT,
    COUNT(GS.ID) AS TIMES_PLAYED,
    SUM(CASE WHEN GST.NAME = 'solved' THEN 1 ELSE 0 END) AS TIMES_SOLVED
FROM PUZZLES PZ
JOIN PUZZLE_SIZES PS ON PZ.PUZZLE_SIZE_ID = PS.ID
JOIN DIFFICULTY_LEVELS DL ON PZ.DIFFICULTY_ID = DL.ID
LEFT JOIN GAME_SESSIONS GS ON PZ.ID = GS.PUZZLE_ID
LEFT JOIN GAME_STATUSES GST ON GS.STATUS_ID = GST.ID
GROUP BY
    PZ.ID, PZ.SEED, PS.GRID_SIZE, DL.NAME, DL.SHUFFLE_MOVES,
    PS.DEFAULT_TIME_LIMIT, PZ.IS_DAILY, PZ.CREATED_AT;


-- V_DAILY
CREATE OR REPLACE VIEW V_DAILY AS
SELECT
    PZ.ID AS PUZZLE_ID,
    PZ.SEED,
    PS.GRID_SIZE,
    DL.NAME AS DIFFICULTY,
    U.USERNAME,
    GST.NAME AS STATUS,
    GS.STEPS_COUNT,
    ROUND((GS.END_TIME - GS.START_TIME) * 24 * 60, 1) AS TIME_MINUTES,
    GS.START_TIME,
    GS.END_TIME,
    RANK() OVER (
        ORDER BY
            CASE WHEN GST.NAME = 'solved' THEN 0 ELSE 1 END,
            GS.STEPS_COUNT
    ) AS PLACE
FROM PUZZLES PZ
JOIN PUZZLE_SIZES PS ON PZ.PUZZLE_SIZE_ID = PS.ID
JOIN DIFFICULTY_LEVELS DL ON PZ.DIFFICULTY_ID = DL.ID
LEFT JOIN GAME_SESSIONS GS ON PZ.ID = GS.PUZZLE_ID
LEFT JOIN USERS U ON GS.USER_ID = U.ID
LEFT JOIN GAME_STATUSES GST ON GS.STATUS_ID = GST.ID
WHERE PZ.IS_DAILY = 1
AND (GST.NAME IS NULL OR GST.NAME != 'active');


-- V_SESSION_RESULTS

CREATE OR REPLACE VIEW V_SESSION_RESULTS AS
SELECT
    GS.ID AS SESSION_ID,
    U.USERNAME,
    PS.GRID_SIZE,
    DL.NAME AS DIFFICULTY,
    GST.NAME AS STATUS,
    GS.STEPS_COUNT,
    ROUND((GS.END_TIME - GS.START_TIME) * 24 * 60, 1) AS TIME_MINUTES,
    GS.START_TIME,
    GS.END_TIME,
    CASE WHEN PZ.IS_DAILY = 1 THEN 'Да' ELSE 'Нет' END AS IS_DAILY,
    RANK() OVER (
        PARTITION BY PZ.PUZZLE_SIZE_ID, PZ.DIFFICULTY_ID
        ORDER BY
            CASE WHEN GST.NAME = 'solved' THEN 0 ELSE 1 END,
            GS.STEPS_COUNT
    ) AS RANK_IN_CATEGORY
FROM GAME_SESSIONS GS
JOIN USERS U ON GS.USER_ID = U.ID
JOIN GAME_STATUSES GST ON GS.STATUS_ID = GST.ID
JOIN PUZZLES PZ ON GS.PUZZLE_ID = PZ.ID
JOIN PUZZLE_SIZES PS ON PZ.PUZZLE_SIZE_ID = PS.ID
JOIN DIFFICULTY_LEVELS DL ON PZ.DIFFICULTY_ID = DL.ID
WHERE GST.NAME != 'active';


-- V_LOGS

CREATE OR REPLACE VIEW V_LOGS AS
SELECT
    L.ID,
    L.LOG_DATE,
    L.LOG_TYPE,
    L.PROCEDURE_NAME,
    L.MESSAGE,
    GS.ID AS SESSION_ID,
    U.USERNAME
FROM LOGS L
LEFT JOIN GAME_SESSIONS GS ON L.SESSION_ID = GS.ID
LEFT JOIN USERS U ON GS.USER_ID = U.ID
WHERE L.ID >= (
    SELECT NVL(MAX(ID) - 200, 0) FROM LOGS
)
ORDER BY L.LOG_DATE DESC;